# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/analog" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/angular" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/astro" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/blitz" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/blitztypescript" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/docusaurus" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/docusaurustypescript" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/electron" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/electrontypescript" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/flutterserverpod/serverpod_app_client" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/flutterserverpod/serverpod_app_flutter" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/flutterserverpod/serverpod_app_server" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/flutterweb" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/laravel" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/laravel" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/nest" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/next" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/nextra" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/nextturbopack" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/nexttypescript" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/nexttypescript-t3" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/nexttypescript-t3-turbo" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/node" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/nuxt" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/qwikcity" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/railsreacttypescript/frontend" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/react" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/reacttypescript" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/solid" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/solidtypescript" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/solidstart" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/solidstarttypescript" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/solito" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/storefront-x-app" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/svelte" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
