version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      # day: "sunday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
