version: "3.4"

services:
  node:
    build:
      context: "node/"
    image: node-app
    env_file:
      - "./node/.env"
    ports:
      - 3000:3000

  react:
    build:
      context: "react/"
    image: react-app
    env_file:
      - "./react/.env"
    ports:
      - 4000:3000

  angular:
    build:
      context: "angular/"
    image: angular-app
    env_file:
      - "./angular/.env"
    ports:
      - 8080:3000

  vue:
    build:
      context: "vue/"
    image: vue-app
    env_file:
      - "./vue/.env"
    ports:
      - 8081:3000
