source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.0.4'
# gem 'rails', '~> 6.0.3'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.4', '>= 1.4.5'
# Use Puma as the app server
gem 'puma', '~> 6.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', '~> 0.6.3', platforms: :ruby

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5.2', '>= 5.2.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.11', '>= 2.11.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 5.0', '>= 5.0.5'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1', '>= 3.1.18'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.11'

# Use Capistrano for deployment
# gem 'capistrano-rails', '~> 1.6', '>= 1.6.2', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.14', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 11.1', '>= 11.1.3', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '~> 4.2'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 3.0'
  gem 'listen', '~> 3.7', '>= 3.7.1'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 4.1'
  gem 'spring-watcher-listen', '~> 2.1'
end

group :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', '~> 1.6', '>= 1.6.3', platforms: %i[ mri mingw x64_mingw ]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 3.38'
  gem 'selenium-webdriver', '~> 4.6', '>= 4.6.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', '~> 1.2022', '>= 1.2022.6', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'rack-cors', '~> 1.1', '>= 1.1.1', require: 'rack/cors'
