/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StartTestImport } from './routes/start-test'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StartTestRoute = StartTestImport.update({
  id: '/start-test',
  path: '/start-test',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/start-test': {
      id: '/start-test'
      path: '/start-test'
      fullPath: '/start-test'
      preLoaderRoute: typeof StartTestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/start-test': typeof StartTestRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start-test': typeof StartTestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/start-test': typeof StartTestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/start-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/start-test'
  id: '__root__' | '/' | '/start-test'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StartTestRoute: typeof StartTestRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StartTestRoute: StartTestRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/start-test"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/start-test": {
      "filePath": "start-test.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
